# Site settings
title: SRIDHAR
twitter_username: rob_hinds
name: Sridhara Murthy B S

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://sridharmbs.github.io/
 - title: LinkedIn
   url: https://www.linkedin.com/in/sridharamurthy/
 

#Any buzzword skills you want to include
skills:
 - Scrum 
 - SAFe 6.0 Agile 
 - Selenium 
 - Postman
 - Appium
 - TestNG
 - SOAP UI
 - Core Java
 - SQL
roles:
 - title: Scrum Master QA Manager
   start: 2022
   end: Ongoing
   employer: QubiQ3
   description: Working as Scrum Master CSM Certified for the past 6 years with  SCRUM and SAFe Agile Framework experience .Also have fair knowledge of Kanban, Crystal and XP Agile Framework.Performed higher level of Project Management also. 
  

 - title: Scrum Master QA Manager
   start: 2021
   end: 2022
   employer: Nous Infosystems
   description: Working as Scrum Master CSM Certified for the past 6 years with  SCRUM and SAFe Agile Framework experience .Also have fair knowledge of Kanban, Crystal and XP Agile Framework.Performed higher level of Project Management also. 
   

   
 - title: Test Manager Project Manager
   start: 2010
   end: 2021
   employer: Mindtree
   description: Project Manager /Test Manager Test Lead ( Jan 2014- Dec 2016) Test Specialist (Jan 2012-Dec 2013) 	Sr .Test Engineer (Oct 2010-Dec 2011)

     
 - title: Sr Test Engineer
   start: 2010
   end: 2021
   employer: Mindtree
   description: Project Manager /Test Manager Test Lead ( Jan 2014- Dec 2016) Test Specialist (Jan 2012-Dec 2013) 	Sr .Test Engineer (Oct 2010-Dec 2011)


 - title: Sr Test Engineer
   start: 2007
   end:  2010
   employer: HP EDS 
   description: Worked for Sumitomo Mitsui Banking Corporation (SMBC) as Sr Test engineer in Banking domain  

      

#Education is required
education:
 - level: Bachelor of Engineering (B.E)
   date: 2005
   subject: Civil Engineering
   school: Visveswaraih Institute of Technology
   

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>Scala</strong>: Working as Scrum Master (CSM Certified) for the past 6 years with SCRUM and SAFe Agile Framework experience. Also have fair knowledge of Kanban, Crystal and XP Agile Framework. Performed higher level of Project Management also.

   <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. I have worked with Spring 4, Spring Boot, JPA (Hibernate and EclipseLink) in addition to others. <br/><br/>
   <strong>Groovy</strong> I have used Groovy as a language in production for ~4 years and I am familiar with many of the languages features (such as writing <a target='_blank' href="https://dzone.com/articles/functional-programming-groovy">Functional Programming style groovy</a>) and quirks (such as <a target="_blank" href="https://dzone.com/articles/groovy-retrospective-an-addendum-memory-usage-perm">memory leak issues</a>). <br/><br/>
   <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/05/serverless-with-aws-lambda-scala.html">Lambda</a> and its more recent <a target="_blank" href="https://automateddeveloper.blogspot.com/2018/10/machine-learning-with-aws-scala.html">Machine Learning capabilities</a>.<br/><br/>
   <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS, Backbone/Underscore/Require. More recently I have written React applications (primarily using the Create React App framework, and extending them)<br/><br/>
   <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
   I have also gained experience and knowledge of other technologies from several side projects and research that I have undertaken in my free time, including Android, a variety of social APIs (Twitter etc) and cloud platforms such as CloudFoundry/OpenShift/AppFog/AWS. <br/><br/>
   As part of Nerdability, I created, and am now primary contributor to, two Spring projects - <a target='_blank' href="https://github.com/robhinds/spring-social-geeklist">Spring-Social-Geeklist</a> and <a target='_blank' href="https://github.com/nerdability/spring-social-khan-academy">Spring-Social-Khan-Academy</a>, which provide core integration with those third-party APIs on top of the Spring Social framework. They are both listed as community projects: <a target='_blank' href="https://projects.spring.io/spring-social/">https://projects.spring.io/spring-social/</a>. <br/><br/>
   I write a blog covering technical and opinion articles that can be found here: <a target='_blank' href="https://automateddeveloper.blogspot.com/">automateddeveloper.blogspot.com</a> (I am also a <a target='_blank' href="https://dzone.com/users/899489/rhinds.html">DZone MVB</a>)

