# Site settings
title: SRIDHAR
twitter_username: rob_hinds
name: Sridhara Murthy B S

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://sridharmbs.github.io/
 - title: LinkedIn
   url: https://www.linkedin.com/in/sridharamurthy/
 

#Any buzzword skills you want to include
skills:
 - Scrum 
 - SAFe 6.0 Agile 
 - Selenium 
 - Postman
 - Appium
 - TestNG
 - SOAP UI
 - Core Java
 - SQL
roles:
 - title: Scrum Master QA Manager
   start: 2022
   end: Ongoing
   employer: QubiQ3
   description: Working as Scrum Master CSM Certified for the past 6 years with  SCRUM and SAFe Agile Framework experience .Also have fair knowledge of Kanban, Crystal and XP Agile Framework.Performed higher level of Project Management also. 
  

 - title: Scrum Master QA Manager
   start: 2021
   end: 2022
   employer: Nous Infosystems
   description: Working as Scrum Master CSM Certified for the past 6 years with  SCRUM and SAFe Agile Framework experience .Also have fair knowledge of Kanban, Crystal and XP Agile Framework.Performed higher level of Project Management also. 
   

   
 - title: Test Manager Project Manager
   start: 2010
   end: 2021
   employer: Mindtree
   description: Project Manager /Test Manager Test Lead ( Jan 2014- Dec 2016) Test Specialist (Jan 2012-Dec 2013) 	Sr .Test Engineer (Oct 2010-Dec 2011)

     
 - title: Sr Test Engineer
   start: 2010
   end:  2010
   employer: Accenture
   description: Worked for BoFA Bank of America Kitty Hawk division as Sr Test engineer in Banking domain

   - title: Sr Test Engineer
   start: 2007
   end:  2010
   employer: HP EDS 
   description: Worked for Sumitomo Mitsui Banking Corporation (SMBC) as Sr Test engineer in Banking domain  
   
   

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
