# Site settings
title: SRIDHAR
twitter_username: rob_hinds
name: Sridhara Murthy B S

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://sridharmbs.github.io/
 - title: LinkedIn
   url: https://www.linkedin.com/in/sridharamurthy/
 

#Any buzzword skills you want to include
skills:
 - Scrum 
 - SAFe 6.0 Agile 
 - Selenium 
 - Postman
 - Appium
 - TestNG
 - SOAP UI
 - Core Java
 - SQL


#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
